language: julia

julia:
  - 1.0
  - 1.3
  - nightly

os:
  - linux
  - osx
  - windows

arch:
  - x64
  - x86

matrix:
  exclude:
    - os: osx
      arch: x86
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage;
              Codecov.submit(process_folder())'